port: 8080
servlet:
  context-path: /employers
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db?serverTimezone=UTC&useSSL=false
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true